CREATE TABLE IF NOT EXISTS interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_id BIGINT,
    rating FLOAT,
    ts TIMESTAMP WITH TIME ZONE,
    UNIQUE(user_id, event_id)
);

CREATE TABLE IF NOT EXISTS similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT,
    event_b BIGINT,
    score FLOAT,
    ts TIMESTAMP WITH TIME ZONE,
    UNIQUE (event_a, event_b)
);