DROP TABLE if exists comments;

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(2000) NOT NULL,
                                        author_id BIGINT,
                                        event_id BIGINT NOT NULL,
                                        created_on TIMESTAMP,
                                        status VARCHAR(20) NOT NULL
);