server:
  port: 0

aggregator:
  kafka:
    bootstrap-servers: "localhost:9092"
    close-timeout: 5000ms
    producer:
      topic: "stats.events-similarity.v1"
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
        "key.serializer": "org.apache.kafka.common.serialization.VoidSerializer"
        "value.serializer": "ru.yandex.practicum.kafka.serializer.EventSimilaritySerializer"

    consumer:
      topic: "stats.user-actions.v1"
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
        "enable.auto.commit": false
        "group.id": "stats.aggregator.group"
        "client.id": "aggregator.group.main"
        "key.deserializer": "org.apache.kafka.common.serialization.VoidDeserializer"
        "value.deserializer": "ru.yandex.practicum.kafka.serializer.UserActionDeserializer"
      poll-timeout: 100ms

    action-weight:
      view: 0.4
      registered: 0.8
      like: 1.0
