DROP TABLE IF EXISTS participation_requests;

CREATE TABLE IF NOT EXISTS  participation_requests (
                                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       event_id BIGINT NOT NULL,
                                                       requester_id BIGINT NOT NULL,
                                                       status VARCHAR(20) DEFAULT 'PENDING'
                                                           CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
                                                       created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                       UNIQUE (event_id, requester_id)
);