DROP TABLE if exists comments;
DROP TABLE if exists event_views;
DROP TABLE if exists compilation_events;
DROP TABLE if exists compilations;
DROP TABLE if exists participation_requests;
DROP TABLE if exists events;
DROP TABLE if exists categories;
DROP TABLE if exists users;
DROP TABLE if exists comments;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(254) NOT NULL UNIQUE,
                                     name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      title VARCHAR(120) NOT NULL,
                                      annotation VARCHAR(2000) NOT NULL,
                                      description VARCHAR(7000),
                                      event_date TIMESTAMP NOT NULL,
                                      created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      published_on TIMESTAMP NULL,
                                      location_lat FLOAT NOT NULL,
                                      location_lon FLOAT NOT NULL,
                                      paid BOOLEAN DEFAULT FALSE,
                                      participant_limit INTEGER DEFAULT 0,
                                      request_moderation BOOLEAN DEFAULT TRUE,
                                      state VARCHAR(20) DEFAULT 'PENDING'
                                          CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
                                      views BIGINT DEFAULT 0,
                                      category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
                                      initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  participation_requests (
                                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                                                       requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                                       status VARCHAR(20) DEFAULT 'PENDING'
                                                           CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
                                                       created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                                       UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS  compilations (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             title VARCHAR(50) NOT NULL UNIQUE,
                                             pinned BOOLEAN DEFAULT FALSE,
                                             created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS  compilation_events (
                                                   compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
                                                   event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                                                   PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS  event_views (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                                            date DATE NOT NULL,
                                            ip VARCHAR(15) NOT NULL,
                                            UNIQUE (event_id, date, ip)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(2000) NOT NULL,
                                        author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                        event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
                                        created_on TIMESTAMP,
                                        status VARCHAR(20) NOT NULL
);